### ISSUE TITLE
Not sure what is going on here but it is a bug in the newest build.

### ISSUE THREAD

**Issue by michaelcrossland1979** [ThioJoe/Full-Stack-AI-Meme-Generator#10]
==================== AI Meme Generator - 1.0.2 ====================

Enter a meme subject or concept (Or just hit enter to let the AI decide)
 >  Strar Trek OTS Kirk hears that he is going to have to have his butt worked on by Bones to save his life.

Enter the number of memes to create (Or just hit Enter for 1):
 >  2

----------------------------------------------------------------------------------------------------
Generating meme 1 of 2...
Sending request to write meme...
Traceback (most recent call last):
  File "AIMemeGenerator.py", line 713, in <module>
  File "AIMemeGenerator.py", line 704, in generate
  File "AIMemeGenerator.py", line 672, in single_meme_generation_loop
  File "AIMemeGenerator.py", line 431, in send_and_receive_message
  File "openai\api_resources\chat_completion.py", line 25, in create
  File "openai\api_resources\abstract\engine_api_resource.py", line 153, in create
  File "openai\api_requestor.py", line 298, in request
  File "openai\api_requestor.py", line 700, in _interpret_response
  File "openai\api_requestor.py", line 763, in _interpret_response_line
openai.error.InvalidRequestError: The model: `gpt-4` does not exist
[17024] Failed to execute script 'AIMemeGenerator' due to unhandled exception!

[process exited with code 1 (0x00000001)]

That is the whole of what I gave it and what it shot backout at me. I'm on Windows 11 Pro fully up to date not a fast ring and have over 25GB of free RAM and not a thing using the CPU or GPU or the internet where I am at.

**Comment by isaacweber613** [comment]
yes i had the same problem it needs to be fixed.
for a temporary solution you can go into the settings file and change where it says to use gpt-4 to somthing like "gpt-3.5-turbo"
I hope this is fixed soon as it really confused me untill I figured this out.

**Comment by michaelcrossland1979** [comment]
yeah I changed it to the other one Joe had listed and got `openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.
[10160] Failed to execute script 'AIMemeGenerator' due to unhandled exception!`
Given to me so it maybe that it's there just not telling us go pay them first.

**Comment by isaacweber613** [comment]
yes you need to set up payment it costs about two cents per meme.
what i did i put in my credit card then under billing - usage limits you can set a limit how much is the max you want to spend per month so you don't go broke.

**Comment by michaelcrossland1979** [comment]
As a follow up on this Joe the OpenAI API page for rates only have

>
MODEL | TPM | RPM | RPD
CHAT
gpt-3.5-turbo | 40,000 | 3 | 200
gpt-3.5-turbo-0301 | 40,000 | 3 | 200
gpt-3.5-turbo-0613 | 40,000 | 3 | 200
gpt-3.5-turbo-16k | 40,000 | 3 | 200
gpt-3.5-turbo-16k-0613 | 40,000 | 3 | 200

Listed as the models that anyone can get to with just signing up. Might want change the settings.ini so that it don't keep trying to use one that is not out for everyone to use just yet but keep up the great work.

**Comment by RileyDevGithub** [comment]
I have the same error. Full terminal: 
==================== AI Meme Generator - 1.0.2 ====================

Enter a meme subject or concept (Or just hit enter to let the AI decide)
 >

Enter the number of memes to create (Or just hit Enter for 1):
 >

----------------------------------------------------------------------------------------------------
Generating meme 1 of 1...
Sending request to write meme...
Traceback (most recent call last):
  File "AIMemeGenerator.py", line 713, in <module>
  File "AIMemeGenerator.py", line 704, in generate
  File "AIMemeGenerator.py", line 672, in single_meme_generation_loop
  File "AIMemeGenerator.py", line 431, in send_and_receive_message
  File "openai\api_resources\chat_completion.py", line 25, in create
  File "openai\api_resources\abstract\engine_api_resource.py", line 153, in create
  File "openai\api_requestor.py", line 298, in request
  File "openai\api_requestor.py", line 700, in _interpret_response
  File "openai\api_requestor.py", line 763, in _interpret_response_line
openai.error.InvalidRequestError: The model: `gpt-4` does not exist
[10076] Failed to execute script 'AIMemeGenerator' due to unhandled exception!

**Comment by ThioJoe** [comment]
Hm it seems they grant access after you've spent $1 on the API: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4

**Comment by michaelcrossland1979** [comment]
Still might want to set the default to one the ones that everyone will get
use without having to sign up for a business account with them right out of
the gate.

**Comment by ThioJoe** [comment]
I updated the messaging in 1.0.3 so that when this error is given, it explains the cause. So I'll convert this to a discussion
