### ISSUE TITLE
I tried forking the code and tried to make it generate images instead of just memes

### ISSUE THREAD

**Issue by ParaliyzedEvo** [ThioJoe/Full-Stack-AI-Meme-Generator#14]
Pretty much I wanted to change the code to generate images and got this error

Sending request to write image...
Traceback (most recent call last):
  File "C:\Users\paral\Documents\Codes that I actually wrote\Python\AIMemeGenerator.py", line 713, in <module>
    generate()
  File "C:\Users\paral\Documents\Codes that I actually wrote\Python\AIMemeGenerator.py", line 704, in generate
    imageInfoDict = single_image_generation_loop()
  File "C:\Users\paral\Documents\Codes that I actually wrote\Python\AIMemeGenerator.py", line 672, in single_image_generation_loop
    chatResponse = send_and_receive_message(text_model, userEnteredPrompt, conversation, temperature)
  File "C:\Users\paral\Documents\Codes that I actually wrote\Python\AIMemeGenerator.py", line 431, in send_and_receive_message
    chatResponse = openai.ChatCompletion.create(
  File "C:\Users\paral\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\paral\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Users\paral\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Users\paral\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\paral\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The model: `gpt-4` does not exist

Here is the [code](https://github.com/ParaliyzedEvo/Full-Stack-AI-Image-Generator) I worked on and hope you can help me, if not imma scrap the whole thing.

**Comment by ThioJoe** [comment]
It's possible you don't have access to the GPT-4 API, I think they grant it to anyone who makes a $1 payment or something: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4 . So many try it with gpt 3.5 for a bit first

**Comment by ParaliyzedEvo** [comment]
> It's possible you don't have access to the GPT-4 API, I think they grant it to anyone who makes a $1 payment or something: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4 . So many try it with gpt 3.5 for a bit first

Yup that was exactly the problem. thanks!
