### ISSUE TITLE
Program crashes right after starting up - v1.0.1 / 1.0.2

### ISSUE THREAD

**Issue by NotDreppy** [ThioJoe/Full-Stack-AI-Meme-Generator#15]
I don't know if it's something wrong with my computer's language settings or whatever because I don't use English by default,
but the program crashes with the following error code right after starting up:

Traceback (most recent call last):
  File "AIMemeGenerator.py", line 713, in <module>
  File "AIMemeGenerator.py", line 601, in generate
  File "AIMemeGenerator.py", line 200, in get_api_keys
  File "AIMemeGenerator.py", line 131, in get_config
  File "configparser.py", line 699, in read
  File "configparser.py", line 1022, in _read
UnicodeDecodeError: 'cp950' codec can't decode byte 0xe2 in position 83: illegal multibyte sequence
[4444] Failed to execute script 'AIMemeGenerator' due to unhandled exception!

Specifications:
CPU: AMD Ryzen 5 3600XT (6-Core) (AMD64)
RAM: Total 64GB (56GB available)
Network: Realtek PCIe GbE Ethernet

Operating System:
Microsoft Windows 11 Pro, version 22H2 (Build 10.0.22621.1992)

![image](https://github.com/ThioJoe/Full-Stack-AI-Meme-Generator/assets/93709292/f8069dee-da10-4f7d-a0a2-d9766198d859)

**Comment by ThioJoe** [comment]
Ok _should_ be fixed in the latest 1.0.3 but let me know if it still does it
